# -*- coding: utf-8 -*-
"""Entrega 5 e 6- arvore 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QjOEIIxHRkXasfamalAVm0erovuS-e7F
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv("student_exam_scores.csv")

X = df.iloc[:, [1,2,3,4]]
y = df.iloc[:, 5]



X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

reg = DecisionTreeRegressor(random_state=42)
reg.fit(X_train, y_train)

y_pred = reg.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Erro quadrático médio (Regressor): {mse:.4f}")
print(f"R² score (Regressor): {r2:.4f}")